django_apps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include("poll.urls"))
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='details'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/results/', views.ResultView.as_view(), name='results')

]

poll/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib import admin


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def check_recency(self):
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= timezone.now()

    def __str__(self):
        return f'Question:{self.question_text}'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=70)
    votes = models.IntegerField(default=0)

poll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_questions'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    template_name = 'poll/details.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultView(generic.DetailView):
    model = Question
    template_name = 'poll/result.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        choice = question.choice_set.get(pk=request.POST["choice"])

    except (KeyError, Choice.DoesNotExist):
        return render(request, 'poll/details.html', {
            'question': question,
            'error_msg': 'Choice not selected'
        })
    choice.votes += 1
    choice.save()

    return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

poll/templates/poll/details.html
{% extends 'poll/layout.html' %}

{% block body %}

<form action="{%url 'poll:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{question.question_text}}</h1></legend>
        {% if error_msg %}<p>{{error_msg}}</p> {% endif %}

        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{choice.id}}" value="{{choice.id}}">
        <label for="choice{{choice.id}}">{{choice.choice_text}}</label>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
{% endblock %}

poll/templates/poll/index.html
{% extends 'poll/layout.html' %}

{% block body %}
<h1>Welcome to the App</h1>
{% if latest_questions %}
<ul>
    {% for question in latest_questions %}
    <li><a href="{% url 'poll:details' question.id %}">{{question}}</a></li>
    {% endfor %}
</ul>
{% else %}
<h4>No polls are available</h4>
{% endif %}
{% endblock %}

poll/templates/poll/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  {% block head %}
  {% endblock %}
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
</html>

poll/templates/poll/result.html
{% extends 'poll/layout.html' %}

{% block body %}
<h1>Results</h1>

<ol>
    {% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}

    <a href="{% url 'poll:details' question.id %}">Click here to go back</a>

</ol>

{% endblock %}